import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Link } from "wouter";
import { 
  Zap, 
  Calculator, 
  CheckCircle, 
  ArrowRightLeft, 
  DollarSign, 
  FileText, 
  Clock, 
  Shield,
  Home,
  Building,
  TrendingUp,
  Info
} from "lucide-react";

export default function NetMetering() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-white">
      {/* Hero Section */}
      <section className="relative py-20 bg-gradient-to-r from-solar-orange to-solar-green overflow-hidden">
        <div className="absolute inset-0 bg-black/10"></div>
        <div className="container mx-auto px-4 relative z-10">
          <div className="max-w-4xl mx-auto text-center text-white">
            <h1 className="text-5xl md:text-6xl font-bold mb-6 leading-tight">
              Net Metering in Pakistan
            </h1>
            <p className="text-xl md:text-2xl mb-8 opacity-90">
              Sell excess solar energy back to the grid and reduce your electricity bills to zero
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Button 
                size="lg" 
                className="bg-white text-solar-orange hover:bg-gray-100 text-lg px-8 py-6"
                asChild
              >
                <Link href="/quote">Get Net Metering Quote</Link>
              </Button>
              <Button 
                size="lg" 
                variant="outline" 
                className="border-white text-white hover:bg-white hover:text-solar-orange text-lg px-8 py-6"
                asChild
              >
                <Link href="/contact">Apply for Net Metering</Link>
              </Button>
            </div>
          </div>
        </div>
      </section>

      {/* What is Net Metering */}
      <section className="py-20 bg-white">
        <div className="container mx-auto px-4">
          <div className="max-w-6xl mx-auto">
            <div className="text-center mb-16">
              <h2 className="text-4xl font-bold text-neutral-dark mb-4">
                What is Net Metering?
              </h2>
              <p className="text-xl text-neutral-600 max-w-3xl mx-auto">
                Net metering allows you to sell excess electricity generated by your solar panels back to the national grid, 
                earning credits that offset your future electricity bills.
              </p>
            </div>

            <div className="grid md:grid-cols-2 gap-12 items-center">
              <div className="space-y-6">
                <div className="flex items-start space-x-4">
                  <div className="bg-solar-orange/10 p-3 rounded-lg">
                    <Zap className="h-6 w-6 text-solar-orange" />
                  </div>
                  <div>
                    <h3 className="text-xl font-semibold text-neutral-dark mb-2">
                      Generate Solar Energy
                    </h3>
                    <p className="text-neutral-600">
                      Your solar panels produce clean electricity during daylight hours
                    </p>
                  </div>
                </div>

                <div className="flex items-start space-x-4">
                  <div className="bg-solar-green/10 p-3 rounded-lg">
                    <Home className="h-6 w-6 text-solar-green" />
                  </div>
                  <div>
                    <h3 className="text-xl font-semibold text-neutral-dark mb-2">
                      Power Your Home
                    </h3>
                    <p className="text-neutral-600">
                      Use the electricity to power your home appliances and lighting
                    </p>
                  </div>
                </div>

                <div className="flex items-start space-x-4">
                  <div className="bg-blue-100 p-3 rounded-lg">
                    <ArrowRightLeft className="h-6 w-6 text-blue-600" />
                  </div>
                  <div>
                    <h3 className="text-xl font-semibold text-neutral-dark mb-2">
                      Export Excess Energy
                    </h3>
                    <p className="text-neutral-600">
                      Send surplus electricity to the grid and earn credits on your bill
                    </p>
                  </div>
                </div>

                <div className="flex items-start space-x-4">
                  <div className="bg-green-100 p-3 rounded-lg">
                    <DollarSign className="h-6 w-6 text-green-600" />
                  </div>
                  <div>
                    <h3 className="text-xl font-semibold text-neutral-dark mb-2">
                      Reduce Your Bill
                    </h3>
                    <p className="text-neutral-600">
                      Credits offset your electricity consumption, potentially reducing bills to zero
                    </p>
                  </div>
                </div>
              </div>

              <div className="bg-gradient-to-br from-solar-orange/10 to-solar-green/10 p-8 rounded-2xl">
                <div className="text-center">
                  <div className="bg-white p-6 rounded-xl mb-6 shadow-sm">
                    <TrendingUp className="h-12 w-12 text-solar-green mx-auto mb-4" />
                    <h3 className="text-2xl font-bold text-neutral-dark mb-2">
                      Save Up to 90%
                    </h3>
                    <p className="text-neutral-600">
                      On your monthly electricity bills with net metering
                    </p>
                  </div>
                  <div className="space-y-3 text-sm">
                    <div className="flex justify-between">
                      <span>Average Monthly Bill:</span>
                      <span className="font-semibold">PKR 25,000</span>
                    </div>
                    <div className="flex justify-between">
                      <span>With Net Metering:</span>
                      <span className="font-semibold text-solar-green">PKR 2,500</span>
                    </div>
                    <div className="border-t pt-2 flex justify-between font-bold">
                      <span>Monthly Savings:</span>
                      <span className="text-solar-green">PKR 22,500</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Net Metering Process */}
      <section className="py-20 bg-gray-50">
        <div className="container mx-auto px-4">
          <div className="max-w-6xl mx-auto">
            <div className="text-center mb-16">
              <h2 className="text-4xl font-bold text-neutral-dark mb-4">
                Net Metering Process in Pakistan
              </h2>
              <p className="text-xl text-neutral-600">
                Follow these simple steps to start earning from your solar investment
              </p>
            </div>

            <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
              <Card className="text-center hover:shadow-lg transition-shadow">
                <CardHeader>
                  <div className="bg-solar-orange/10 p-4 rounded-full w-16 h-16 mx-auto mb-4">
                    <FileText className="h-8 w-8 text-solar-orange mx-auto" />
                  </div>
                  <CardTitle className="text-lg">1. Application</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-neutral-600">
                    Submit net metering application to your local DISCO (Distribution Company)
                  </p>
                </CardContent>
              </Card>

              <Card className="text-center hover:shadow-lg transition-shadow">
                <CardHeader>
                  <div className="bg-solar-green/10 p-4 rounded-full w-16 h-16 mx-auto mb-4">
                    <Shield className="h-8 w-8 text-solar-green mx-auto" />
                  </div>
                  <CardTitle className="text-lg">2. Approval</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-neutral-600">
                    Get technical approval and interconnection agreement from DISCO
                  </p>
                </CardContent>
              </Card>

              <Card className="text-center hover:shadow-lg transition-shadow">
                <CardHeader>
                  <div className="bg-blue-100 p-4 rounded-full w-16 h-16 mx-auto mb-4">
                    <Zap className="h-8 w-8 text-blue-600 mx-auto" />
                  </div>
                  <CardTitle className="text-lg">3. Installation</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-neutral-600">
                    Install solar system and bidirectional meter by certified technicians
                  </p>
                </CardContent>
              </Card>

              <Card className="text-center hover:shadow-lg transition-shadow">
                <CardHeader>
                  <div className="bg-green-100 p-4 rounded-full w-16 h-16 mx-auto mb-4">
                    <CheckCircle className="h-8 w-8 text-green-600 mx-auto" />
                  </div>
                  <CardTitle className="text-lg">4. Commissioning</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-neutral-600">
                    System testing, commissioning, and start earning from day one
                  </p>
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      </section>

      {/* Benefits & Requirements */}
      <section className="py-20 bg-white">
        <div className="container mx-auto px-4">
          <div className="max-w-6xl mx-auto">
            <div className="grid lg:grid-cols-2 gap-12">
              {/* Benefits */}
              <div>
                <h2 className="text-3xl font-bold text-neutral-dark mb-8">
                  Benefits of Net Metering
                </h2>
                <div className="space-y-6">
                  <div className="flex items-start space-x-4">
                    <CheckCircle className="h-6 w-6 text-solar-green mt-1" />
                    <div>
                      <h3 className="text-xl font-semibold text-neutral-dark mb-2">
                        Reduce Electricity Bills
                      </h3>
                      <p className="text-neutral-600">
                        Offset your electricity consumption with solar credits and reduce bills up to 90%
                      </p>
                    </div>
                  </div>

                  <div className="flex items-start space-x-4">
                    <CheckCircle className="h-6 w-6 text-solar-green mt-1" />
                    <div>
                      <h3 className="text-xl font-semibold text-neutral-dark mb-2">
                        Earn from Excess Generation
                      </h3>
                      <p className="text-neutral-600">
                        Get paid for surplus electricity you export to the national grid
                      </p>
                    </div>
                  </div>

                  <div className="flex items-start space-x-4">
                    <CheckCircle className="h-6 w-6 text-solar-green mt-1" />
                    <div>
                      <h3 className="text-xl font-semibold text-neutral-dark mb-2">
                        Environmental Impact
                      </h3>
                      <p className="text-neutral-600">
                        Contribute to Pakistan's renewable energy goals and reduce carbon footprint
                      </p>
                    </div>
                  </div>

                  <div className="flex items-start space-x-4">
                    <CheckCircle className="h-6 w-6 text-solar-green mt-1" />
                    <div>
                      <h3 className="text-xl font-semibold text-neutral-dark mb-2">
                        Energy Independence
                      </h3>
                      <p className="text-neutral-600">
                        Reduce dependence on grid electricity and protect against rising energy costs
                      </p>
                    </div>
                  </div>
                </div>
              </div>

              {/* Requirements */}
              <div>
                <h2 className="text-3xl font-bold text-neutral-dark mb-8">
                  Net Metering Requirements
                </h2>
                <div className="space-y-6">
                  <div className="flex items-start space-x-4">
                    <Info className="h-6 w-6 text-solar-orange mt-1" />
                    <div>
                      <h3 className="text-xl font-semibold text-neutral-dark mb-2">
                        System Size Limit
                      </h3>
                      <p className="text-neutral-600">
                        Maximum 1MW for commercial and no limit for residential connections
                      </p>
                    </div>
                  </div>

                  <div className="flex items-start space-x-4">
                    <Info className="h-6 w-6 text-solar-orange mt-1" />
                    <div>
                      <h3 className="text-xl font-semibold text-neutral-dark mb-2">
                        Bidirectional Meter
                      </h3>
                      <p className="text-neutral-600">
                        Installation of bidirectional meter to measure import and export energy
                      </p>
                    </div>
                  </div>

                  <div className="flex items-start space-x-4">
                    <Info className="h-6 w-6 text-solar-orange mt-1" />
                    <div>
                      <h3 className="text-xl font-semibold text-neutral-dark mb-2">
                        Safety Standards
                      </h3>
                      <p className="text-neutral-600">
                        Compliance with IEEE 1547 and IEC 61727 standards for grid interconnection
                      </p>
                    </div>
                  </div>

                  <div className="flex items-start space-x-4">
                    <Info className="h-6 w-6 text-solar-orange mt-1" />
                    <div>
                      <h3 className="text-xl font-semibold text-neutral-dark mb-2">
                        Documentation
                      </h3>
                      <p className="text-neutral-600">
                        Valid electricity connection, property ownership, and technical specifications
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Pakistani DISCOs */}
      <section className="py-20 bg-gray-50">
        <div className="container mx-auto px-4">
          <div className="max-w-6xl mx-auto">
            <div className="text-center mb-16">
              <h2 className="text-4xl font-bold text-neutral-dark mb-4">
                Net Metering by DISCO
              </h2>
              <p className="text-xl text-neutral-600">
                Apply for net metering with your local Distribution Company
              </p>
            </div>

            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
              <Card className="hover:shadow-lg transition-shadow">
                <CardHeader>
                  <CardTitle className="text-lg text-center">LESCO</CardTitle>
                </CardHeader>
                <CardContent className="text-center">
                  <Building className="h-8 w-8 text-solar-orange mx-auto mb-4" />
                  <p className="text-neutral-600 mb-4">
                    Lahore Electric Supply Company
                  </p>
                  <p className="text-sm text-neutral-500">
                    Serving: Lahore, Kasur, Sheikhupura, Nankana Sahib, Okara
                  </p>
                </CardContent>
              </Card>

              <Card className="hover:shadow-lg transition-shadow">
                <CardHeader>
                  <CardTitle className="text-lg text-center">K-Electric</CardTitle>
                </CardHeader>
                <CardContent className="text-center">
                  <Building className="h-8 w-8 text-solar-orange mx-auto mb-4" />
                  <p className="text-neutral-600 mb-4">
                    Karachi Electric Supply Company
                  </p>
                  <p className="text-sm text-neutral-500">
                    Serving: Karachi and surrounding areas
                  </p>
                </CardContent>
              </Card>

              <Card className="hover:shadow-lg transition-shadow">
                <CardHeader>
                  <CardTitle className="text-lg text-center">IESCO</CardTitle>
                </CardHeader>
                <CardContent className="text-center">
                  <Building className="h-8 w-8 text-solar-orange mx-auto mb-4" />
                  <p className="text-neutral-600 mb-4">
                    Islamabad Electric Supply Company
                  </p>
                  <p className="text-sm text-neutral-500">
                    Serving: Islamabad, Rawalpindi, Attock, Jhelum, Chakwal
                  </p>
                </CardContent>
              </Card>

              <Card className="hover:shadow-lg transition-shadow">
                <CardHeader>
                  <CardTitle className="text-lg text-center">FESCO</CardTitle>
                </CardHeader>
                <CardContent className="text-center">
                  <Building className="h-8 w-8 text-solar-orange mx-auto mb-4" />
                  <p className="text-neutral-600 mb-4">
                    Faisalabad Electric Supply Company
                  </p>
                  <p className="text-sm text-neutral-500">
                    Serving: Faisalabad, Jhang, Toba Tek Singh, Chiniot
                  </p>
                </CardContent>
              </Card>

              <Card className="hover:shadow-lg transition-shadow">
                <CardHeader>
                  <CardTitle className="text-lg text-center">GEPCO</CardTitle>
                </CardHeader>
                <CardContent className="text-center">
                  <Building className="h-8 w-8 text-solar-orange mx-auto mb-4" />
                  <p className="text-neutral-600 mb-4">
                    Gujranwala Electric Power Company
                  </p>
                  <p className="text-sm text-neutral-500">
                    Serving: Gujranwala, Sialkot, Narowal, Hafizabad
                  </p>
                </CardContent>
              </Card>

              <Card className="hover:shadow-lg transition-shadow">
                <CardHeader>
                  <CardTitle className="text-lg text-center">MEPCO</CardTitle>
                </CardHeader>
                <CardContent className="text-center">
                  <Building className="h-8 w-8 text-solar-orange mx-auto mb-4" />
                  <p className="text-neutral-600 mb-4">
                    Multan Electric Power Company
                  </p>
                  <p className="text-sm text-neutral-500">
                    Serving: Multan, Bahawalpur, Sahiwal, Vehari
                  </p>
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-gradient-to-r from-solar-orange to-solar-green">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto text-center text-white">
            <h2 className="text-4xl font-bold mb-6">
              Ready to Start Net Metering?
            </h2>
            <p className="text-xl mb-8 opacity-90">
              Let Solar Galaxy handle your complete net metering application process. 
              From paperwork to installation, we've got you covered.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Button 
                size="lg" 
                className="bg-white text-solar-orange hover:bg-gray-100 text-lg px-8 py-6"
                asChild
              >
                <Link href="/quote">Get Free Quote</Link>
              </Button>
              <Button 
                size="lg" 
                variant="outline" 
                className="border-white text-white hover:bg-white hover:text-solar-orange text-lg px-8 py-6"
                asChild
              >
                <Link href="/contact">Contact Our Experts</Link>
              </Button>
            </div>
            <div className="mt-8 flex items-center justify-center space-x-6 text-sm opacity-80">
              <div className="flex items-center">
                <Clock className="h-4 w-4 mr-2" />
                Free Consultation
              </div>
              <div className="flex items-center">
                <Shield className="h-4 w-4 mr-2" />
                Licensed & Certified
              </div>
              <div className="flex items-center">
                <CheckCircle className="h-4 w-4 mr-2" />
                End-to-End Service
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}